var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                     xxxx                                                       ",
   "                     x  x                                                   xx  ",
   "                     x  x                                                    x  ",
   "                     x  x                                                    x  ",
   "           xxxx      x  x                                                    x  ",
   "           x  x      x  x                            xx             o    o   x  ",
   "     @     x  x     bx  x                                                    x  ",
   "xxxxxxxxxxxx  xxxxxxxx  xxxxxxxxxxx    xxxxxxxx              xxxxxxxxxxxxxxxxx  ",
   "                                  x    x      x              x                  ",
   "                                  x!!!!x      x!!!!!!!!!!!!!!x                  ",
   "                                  x!!!!x      x!!!!!!!!!!!!!!x                  ",
   "                                  xxxxxx      xxxxxxxxxxxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                    o                                                           ",
   "     x             xxx                                                          ",
   " xxxxx            xx!xx                                                         ",
   " x                x!!!x                                                         ",
   " x  @             xx!xx                                                         ",
   " xxxxx             xvx                                                          ",
   "     x               xx      xxxx                                               ",
   "     x                xx                                                        ",
   "     x                 x                  o                                     ",
   "     x                 x                                                       x",
   "     x                 x                  t                                    x",
   "     x         xxx     x                 xxx                                   x",
   "     x         x x                                                    o   o    x",
   "     x   o   xxx x          xxxxx                                  o         o x",
   "     x       x   x        xxx   x   t                                          x",
   "     xxxxxxxxx   x     xxxx       xxxxxxx   xxxxxxxxxxxxxxxxxxx                x",
   "                 x     x          x     x   x                 xx               x",
   "                 x!!!!!!!!!!!x    x!!!!xx   xx!!!!!!!!!!!!!!!!!xx              x",
   "                 x!!!!!!!!!!!x    x!!!!x     x!!!!!!!!!!!!!!!!!!xx             x",
   "                 x!!!!!!!!!!!x b  x!!!xx  o  xx!!!!!!!!!!!!!!!!!!xx            x",
   "                 x!!!!!!!!!!!xxxxxx!!!x   x   x!!!!!!!!!!!!!!!!!!!xx           x",
   "                 x!!!!!!!!!!!!!!!!!!!!x!!!!!!!x!!!!!!!!!!!!!!!!!!!!xx      o   x",
   "                 x!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xx         x",
   "                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx"],  
  ["                                                                                                              ",
   " xxxxxxxxxxxxxxxxxxx                                                                                          ",
   " x!!!!!!!!!!!!!!!!!x                                                                                          ",
   " xvxxxvxxxvxxxvxxxxx                                                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "    o   o   o                                                          x                                      ",
   "                                                            o    o    ox                                      ",
   "xx xxx xxx xxx xxxx                                         xxxxxxxxxxxx                                      ",
   "!!!!!!!!!!!!!!!!!!xxx                                       x                                                 ",
   "!!!!!!!!!!!!!!!!!!!!x                                       x                                                 ",
   "!!!!!!!!!!!!!!!!!!!!x                                       x              xxx                                ",
   "!!!!!!!!!!!!!!!!!!!!x       xxxxxxxxxxxx                    x                                                 ",
   "xxvxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!v                    x                                                 ",
   "                            xxxxxxxxxxx                     x                   xx                            ",
   "                             x                              x                 xo!!x                           ",
   "                             x                              x           t      xxv                            ",
   "                             x o                  x   xxxxxxx                                                 ",
   "                             xxxx          xxxxxxxx   x                                                       ",
   "                                          tx          x                                    x  x               ",
   "                              o         xxxx          x                xxxx               x!oo!x              ",
   "                             xxx           x          x               x!oo!x               xxxx               ",
   "                             x             x          x    o           x  x                                   ",
   "                             x             x       !!!x    x                                                  ",
   "                             x             x       xxxx                                                       ",
   "                             x             x          x                                                       ",
   "                             x xxxxxxxxxxx x          x                                                       ",
   "                             x             x          x             xx                                        ",
   "                             x             x          x!!!!x    x!!!!x                   o         o          ",
   " o                           x             x!!!!      x!!!!x    x!!!!x  xx               x         x          ",
   "xxx                          xx           xxxxxx      xxxvxxx   xxxvxx                   x    o    x          ",
   "  x                           x           x                                              x!!!xxx!!!x        o ",
   "  x                           x           x                                              xxvxx xxvxx       xxx",
   "  x                           x           x                                                                x  ",
   "  x                           xo         ox                              xxxxx                             x  ",
   "  xb                          xx         xx     !!!                      x   x                             x  ",
   "  xxxxxx                                  x     xxx        xxxx          x   o                             x  ",
   "  x                                       x                              x                                 x  ",
   "  x                                 o     x                              x                              o  x  ",
   "  x                           xx         xx                             xxx                                x  ",
   "  x                           x    xxx    x o    t                      x x    t                           x  ",
   "  x                           xxxxxxxxxxxxxxxxxxxxxxxx           x oo  xx xx      o      o     o     o     x  ",
   "  x      @       xxxxxxxxxxxxxx                      x!!!!!!!!!!!x    xx   xx                              x  ",
   "  xxxxxxxxxxxxxxxx                                   xxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],  
  ["o             o              o",
   "                              ",
   "                              ",
   "                              ",
   "                              ",
   "      x   x  xxx  x   x       ",
   "       x x  x   x x   x       ",
   "        x   x   x x   x       ",
   "        x   x   x x   x       ",
   "        x    xxx   xxx        ",
   "                              ",
   "                              ",
   "     x     x xxxxx x   x      ",
   "     x     x   x   xx  x      ",
   "     x  x  x   x   x x x      ",
   "     x x x x   x   x  xx      ",
   "      x   x  xxxxx x   x      ",
   " o       o       o       o    ",
   "o  o   o   o   o   o   o   o  ",
   "     o       o @     o       o",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              ",
   "                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
